# Generated by Django 3.1.7 on 2021-02-25 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_field', models.IntegerField()),
                ('decimal_field', models.DecimalField(decimal_places=4, max_digits=10)),
                ('duration_field', models.DurationField()),
                ('file_field', models.DurationField()),
                ('float_field', models.FloatField()),
                ('boolean_field', models.BooleanField()),
                ('json_field', models.JSONField()),
                ('uuid_field', models.UUIDField()),
                ('char_field', models.CharField(max_length=200)),
                ('date_field', models.DateField()),
                ('time_field', models.TimeField()),
                ('date_time_field', models.DateTimeField()),
                ('foreign_key_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_field', to='demo.modelb')),
                ('foreign_key_recursive_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_field', to='demo.modela')),
                ('many_field', models.ManyToManyField(related_name='reverse_many_field', to='demo.ModelB')),
                ('many_recursive_field', models.ManyToManyField(related_name='reverse_many_recursive_field', to='demo.ModelA')),
            ],
        ),
    ]
