# Generated by Django 3.1.7 on 2021-02-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modela',
            name='file_field',
            field=models.FileField(upload_to=''),
        ),
    ]
