# Generated by Django 3.1.7 on 2021-02-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210224_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modela',
            name='date_field',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modela',
            name='date_time_field',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modela',
            name='foreign_key_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_field', to='demo.modelb'),
        ),
        migrations.AlterField(
            model_name='modela',
            name='foreign_key_recursive_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_field', to='demo.modela'),
        ),
        migrations.AlterField(
            model_name='modela',
            name='many_field',
            field=models.ManyToManyField(blank=True, related_name='reverse_many_field', to='demo.ModelB'),
        ),
        migrations.AlterField(
            model_name='modela',
            name='many_recursive_field',
            field=models.ManyToManyField(blank=True, related_name='reverse_many_recursive_field', to='demo.ModelA'),
        ),
        migrations.AlterField(
            model_name='modela',
            name='time_field',
            field=models.TimeField(auto_now=True),
        ),
    ]
